// <auto-generated />
namespace MovieDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddFavoriteFilm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFavoriteFilm));
        
        string IMigrationMetadata.Id
        {
            get { return "202004301205409_AddFavoriteFilm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
